For this hackathon, I chose the TMDB + IMDB Merged Movies Dataset from Kaggle. This dataset combines movie information from The Movie Database (TMDb) and IMDb, providing a comprehensive collection of movie-related data.

It includes a wide range of attributes such as titles, release dates, ratings, genres, production companies, and more, making it a valuable resource for movie analysis, recommendation systems, and other data science applications.

However, before loading the dataset into MySQL, it needed to be cleaned and prepared.

In [ ]:
import pandas as pd

In [ ]:
movies = pd.read_csv('/content/TMDB  IMDB Movies Dataset.csv')

In [ ]:
movies.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2802658,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2505656,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.1,3152839,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,1492000,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,1552648,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436489 entries, 0 to 436488
Data columns (total 29 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    436489 non-null  int64
 1   title                 436489 non-null  object
 2   vote_average          436489 non-null  float64
 3   vote_count            436489 non-null  int64
 4   status                436489 non-null  object
 5   release_date          415101 non-null  object
 6   revenue               436489 non-null  int64
 7   runtime               436489 non-null  int64
 8   adult                 436489 non-null  bool
 9   backdrop_path         185297 non-null  object
 10  budget                436489 non-null  int64
 11  homepage              54781 non-null   object
 12  tconst                436489 non-null  object
 13  original_language     436489 non-null  object
 14  original_title        436489 non-null  object
 15  overview              393504 non-null  object
 16  popularity            436489 non-null  float64
 17  poster_path           360560 non-null  object
 18  tagline               92194 non-null   object
 19  genres                356758 non-null  object
 20  production_companies  261888 non-null  object
 21  production_countries  320697 non-null  object
 22  spoken_languages      332073 non-null  object
 23  keywords              170687 non-null  object
 24  directors             426542 non-null  object
 25  writers               371460 non-null  object
 26  averageRating         436489 non-null  float64
 27  numVotes              436489 non-null  int64
 28  cast                  367675 non-null  object
dtypes: bool(1), float64(3), int64(6), object(19)
memory usage: 93.7+ MB

In [ ]:
movies.describe()

,id,vote_average,vote_count,revenue,runtime,budget,popularity,averageRating,numVotes
count,4.364890e+05,436489.00000,436489.000000,4.364890e+05,436489.000000,4.364890e+05,436489.000000,436489.000000,4.364890e+05
mean,4.937508e+05,3.59889,48.824665,1.651372e+06,66.443849,6.482139e+05,2.192965,6.229077,3.101814e+03
std,3.641247e+05,3.15010,512.555440,2.617460e+07,63.889115,7.410078e+06,11.339458,1.309756,3.397084e+04
min,2.000000e+00,0.00000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.000000,5.000000e+00
25%,2.100930e+05,0.00000,0.000000,0.000000e+00,15.000000,0.000000e+00,0.600000,5.400000,2.300000e+01
50%,4.192690e+05,4.60000,1.000000,0.000000e+00,80.000000,0.000000e+00,0.854000,6.300000,7.000000e+01
75%,7.110990e+05,6.20000,6.000000,0.000000e+00,96.000000,0.000000e+00,1.656000,7.100000,3.190000e+02
max,1.662777e+06,10.00000,34495.000000,2.923706e+09,14400.000000,8.880000e+08,2994.357000,10.000000,3.173846e+06

In [ ]:
print("Dataset Shape:", movies.shape)
print("\nColumn Names:")
print(movies.columns.tolist())

Dataset Shape: (436489, 29)

Column Names:
['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date', 'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage', 'tconst', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'tagline', 'genres', 'production_companies', 'production_countries', 'spoken_languages', 'keywords', 'directors', 'writers', 'averageRating', 'numVotes', 'cast']

In [ ]:
print("Duplicate rows:", movies.duplicated().sum())

Duplicate rows: 0

In [ ]:
movies.isnull().sum()

id                           0
title                        0
vote_average                 0
vote_count                   0
status                       0
release_date             21388
revenue                      0
runtime                      0
adult                        0
backdrop_path           251192
budget                       0
homepage                381708
tconst                       0
original_language            0
original_title               0
overview                 42985
popularity                   0
poster_path              75929
tagline                 344295
genres                   79731
production_companies    174601
production_countries    115792
spoken_languages        104416
keywords                265802
directors                 9947
writers                  65029
averageRating                0
numVotes                     0
cast                     68814
dtype: int64

Since not all columns are required for the movie database, we selected only the essential features needed for generating recommendations, such as genre, ratings, and titles, and created a refined dataset accordingly.

In [ ]:
keep_cols = [
    "id",
    "title",
    "genres",
    "overview",
    "keywords",
    "cast",
    "directors",
    "vote_average",
    "popularity",
    "release_date"
]

In [ ]:
new_movies = movies[keep_cols]

In [ ]:
new_movies.head()

,id,title,genres,overview,keywords,cast,directors,vote_average,popularity,release_date
0,27205,Inception,"Action, Science Fiction, Adventure","Cobb, a skilled thief who commits corporate es...","rescue, mission, dream, airplane, paris, franc...","Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...",Christopher Nolan,8.364,83.952,2010-07-15
1,157336,Interstellar,"Adventure, Drama, Science Fiction",The adventures of a group of explorers who mak...,"rescue, future, spacecraft, race against time,...","Matthew McConaughey, Anne Hathaway, Michael Ca...",Christopher Nolan,8.417,140.241,2014-11-05
2,155,The Dark Knight,"Drama, Action, Crime, Thriller",Batman raises the stakes in his war on crime. ...,"joker, sadism, chaos, secret identity, crime f...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",Christopher Nolan,8.512,130.643,2008-07-16
3,19995,Avatar,"Action, Adventure, Fantasy, Science Fiction","In the 22nd century, a paraplegic Marine is di...","future, society, culture clash, space travel, ...","Sam Worthington, Zoe Saldaña, Sigourney Weaver...",James Cameron,7.573,79.932,2009-12-15
4,24428,The Avengers,"Science Fiction, Action, Adventure",When an unexpected enemy emerges and threatens...,"new york city, superhero, shield, based on com...","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",Joss Whedon,7.710,98.082,2012-04-25

In [ ]:
new_movies.isnull().sum()

id                   0
title                0
genres           79731
overview         42985
keywords        265802
cast             68814
directors         9947
vote_average         0
popularity           0
release_date     21388
dtype: int64

Our most basic column is genre, so we can only delete missing values.

In [ ]:
new_movies = new_movies.dropna(subset=["title", "genres"])

In [ ]:
text_cols = ["overview", "keywords", "cast", "directors"]

for col in text_cols:
    new_movies[col] = new_movies[col].fillna("Unknown")

In [ ]:
new_movies["vote_average"] = new_movies["vote_average"].fillna(new_movies["vote_average"].median())
new_movies["popularity"] = new_movies["popularity"].fillna(new_movies["popularity"].median())

In [ ]:
new_movies["release_date"] = pd.to_datetime(new_movies["release_date"], errors="coerce")

new_movies["year"] = new_movies["release_date"].dt.year
new_movies["year"] = new_movies["year"].fillna(new_movies["year"].median())

In [ ]:
#Remove all extra quotes from all string columns
str_cols = new_movies.select_dtypes(include='object').columns
for col in str_cols:
    new_movies[col] = new_movies[col].str.replace('"', '', regex=False)

In [ ]:
new_movies["content"] = (
    new_movies["genres"] + " " +
    new_movies["keywords"] + " " +
    new_movies["overview"] + " " +
    new_movies["cast"] + " " +
    new_movies["directors"])

In [ ]:
print("Duplicate rows:", new_movies.duplicated().sum())

Duplicate rows: 0

In [ ]:
new_movies.isnull().sum()

id                 0
title              0
genres             0
overview           0
keywords           0
cast               0
directors          0
vote_average       0
popularity         0
release_date    4780
year               0
content            0
dtype: int64

In [ ]:
new_movies["release_date"] = new_movies["release_date"].fillna(
    new_movies["year"].astype(int).astype(str) + "-01-01")

In [ ]:
new_movies.isnull().sum()

id              0
title           0
genres          0
overview        0
keywords        0
cast            0
directors       0
vote_average    0
popularity      0
release_date    0
year            0
content         0
dtype: int64

In [ ]:
#Fix the year column: remove .0 and convert to int
new_movies['year'] = new_movies['year'].astype(float).astype(int)

In [ ]:
cols_to_quote = [col for col in new_movies.columns if col != 'id']
for col in cols_to_quote:
    new_movies[col] = new_movies[col].apply(lambda x: f'"{x}"')

print(new_movies)

            id                                          title  \
0        27205                                    "Inception"
1       157336                                 "Interstellar"
2          155                              "The Dark Knight"
3        19995                                       "Avatar"
4        24428                                 "The Avengers"
...        ...                                            ...
436484  859442                        "May She Rest in Peace"
436485  859454  "Tales of a Gunman: The Man Without Tomorrow"
436486  859462                                      "Namaste"
436487  859477                                  "Lo habitado"
436488  859478                    "The Magnificent Meyersons"

                                               genres  \
0                "Action, Science Fiction, Adventure"
1                 "Adventure, Drama, Science Fiction"
2                    "Drama, Action, Crime, Thriller"
3       "Action, Adventure, Fantasy, Science Fiction"
4                "Science Fiction, Action, Adventure"
...                                               ...
436484                                "Drama, Comedy"
436485                                "Action, Crime"
436486                                      "Romance"
436487                                        "Drama"
436488                                        "Drama"

                                                 overview  \
0       "Cobb, a skilled thief who commits corporate e...
1       "The adventures of a group of explorers who ma...
2       "Batman raises the stakes in his war on crime....
3       "In the 22nd century, a paraplegic Marine is d...
4       "When an unexpected enemy emerges and threaten...
...                                                   ...
436484  "A former bourgeoisie family's preoccupation w...
436485  "The fourth film in the Tales of a Gunman seri...
436486  "Told through the eyes of multiple couples, a ...
436487  "Four teenagers occupy an abandoned house, in ...
436488  "A complicated New York City family as they di...

                                                 keywords  \
0       "rescue, mission, dream, airplane, paris, fran...
1       "rescue, future, spacecraft, race against time...
2       "joker, sadism, chaos, secret identity, crime ...
3       "future, society, culture clash, space travel,...
4       "new york city, superhero, shield, based on co...
...                                                   ...
436484                                       "short film"
436485                                          "Unknown"
436486                                          "Unknown"
436487                                          "Unknown"
436488                                          "Unknown"

                                                     cast  \
0       "Leonardo DiCaprio, Joseph Gordon-Levitt, Ken ...
1       "Matthew McConaughey, Anne Hathaway, Michael C...
2       "Christian Bale, Heath Ledger, Aaron Eckhart, ...
3       "Sam Worthington, Zoe Saldaña, Sigourney Weave...
4       "Robert Downey Jr., Chris Evans, Mark Ruffalo,...
...                                                   ...
436484  "Maede Tahmasbi, Behzad Dorani, Shokoufeh Rahm...
436485  "Keiichirō Akagi, Jō Shishido, Reiko Sasamori,...
436486  "Terry Donahue, Steve Blackwood, Ian Lyons, Ja...
436487                                    "Gonzalo Casco"
436488  "Kate Mulgrew, Richard Kind, Ian Kahn, Jackie ...

                     directors vote_average popularity           release_date  \
0          "Christopher Nolan"      "8.364"   "83.952"  "2010-07-15 00:00:00"
1          "Christopher Nolan"      "8.417"  "140.241"  "2014-11-05 00:00:00"
2          "Christopher Nolan"      "8.512"  "130.643"  "2008-07-16 00:00:00"
3              "James Cameron"      "7.573"   "79.932"  "2009-12-15 00:00:00"
4                "Joss Whedon"       "7.71"   "98.082"  "2012-04-25 00:00:00"
...                        ...          ...        ...                    ...
436484        "Nazgol Kashani"        "0.0"      "0.6"  "2021-07-14 00:00:00"
436485       "Hiroshi Noguchi"        "0.0"    "0.646"  "1960-12-03 00:00:00"
436486       "Christine Altan"        "0.0"      "0.6"  "2017-10-12 00:00:00"
436487  "Martín Emiliano Díaz"        "0.0"      "0.6"  "2021-08-18 00:00:00"
436488      "Evan Oppenheimer"        "0.0"      "1.4"  "2021-08-20 00:00:00"

          year                                            content
0       "2010"  "Action, Science Fiction, Adventure rescue, mi...
1       "2014"  "Adventure, Drama, Science Fiction rescue, fut...
2       "2008"  "Drama, Action, Crime, Thriller joker, sadism,...
3       "2009"  "Action, Adventure, Fantasy, Science Fiction f...
4       "2012"  "Science Fiction, Action, Adventure new york c...
...        ...                                                ...
436484  "2021"  "Drama, Comedy short film A former bourgeoisie...
436485  "1960"  "Action, Crime Unknown The fourth film in the ...
436486  "2017"  "Romance Unknown Told through the eyes of mult...
436487  "2021"  "Drama Unknown Four teenagers occupy an abando...
436488  "2021"  "Drama Unknown A complicated New York City fam...

[356758 rows x 12 columns]

Now that our database is clean and without duplicates we can save it in .csv format and upload it to MySQL.

In [ ]:
new_movies.to_csv(
    "movies_cleaned.csv",
    index=False,
    encoding="utf-8")